=== szp99/ENZ1ATxmlGyak/ENZ1AT_0922/iskola.dtd
<!DOCTYPE iskola [
	<!ELEMENT iskola (tanar+,tantargy+)>
	<!ELEMENT tanar (nev,szak)>
		<!ATTLIST tanar id ID #REQUIRED>
		<!ELEMENT nev (#PCDATA)>
		<!ELEMENT szak (#PCDATA)>
	<!ELEMENT tantargy (targynev,osztaly)>
		<!ATTLIST tantargy tid ID #REQUIRED>
		<!ATTLIST tantargy tanarid IDREF #REQUIRED>
		<!ELEMENT targynev (#PCDATA)>
		<!ELEMENT osztaly (#PCDATA)>
]>

=== szp99/ENZ1ATxmlGyak/ENZ1AT_0922/iskola.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--<!DOCTYPE iskola SYSTEM "iskola.dtd"> -->

<iskola>
	<tanar id="0">
		<nev>Dr. Bednarik László</nev>
		<szak>Informatika</szak>	
	</tanar>
	<tanar id="1">
		<nev>Fegyverneki Sándor</nev>
		<szak>Matematika</szak>	
	</tanar>
	<tantargy tid="0" tanarid="0">
		<targynev>Operációs rendszerek</targynev>
		<osztaly>BPI</osztaly>
	</tantargy>
	<tantargy tid="1" tanarid="0">
		<targynev>Adatkezelés XML-ben</targynev>
		<osztaly>BPI</osztaly>
	</tantargy>
	<tantargy tid="2" tanarid="1">
		<targynev>Valószínűség számítás</targynev>
		<osztaly>BPI</osztaly>
	</tantargy>
</iskola>
